# Generated by Django 4.2.15 on 2024-08-22 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS dashboard_application;'),
    ]
